version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - /tmp/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: badgrmysqlrootpass
       MYSQL_DATABASE: badgrdb
       MYSQL_USER: badgruser
       MYSQL_PASSWORD: badgrmysqlpass

   badgrserver:
     depends_on:
       - db
     image: eoscsynergy/badgr-server
     ports:
       - "8000:8000"
       - "8443:8443"
     volumes:
       - /tmp/badgr/settings_local.py:/badgr/code/apps/mainsite/settings_local.py
       - /tmp/badgr/server.crt:/etc/ssl/certs/server.crt
       - /tmp/badgr/server.key:/etc/ssl/certs/server.key
     restart: always

   badgrui:
     depends_on:
       - badgrserver
     image: eoscsynergy/badgr-ui
     ports:
       - "80:80"
       - "443:443"
     restart: always
     volumes:
       - /tmp/badgr/nginx.conf:/etc/nginx/nginx.conf
       - /tmp/badgr/server.crt:/etc/ssl/certs/server.crt
       - /tmp/badgr/server.key:/etc/ssl/certs/server.key
     environment:
       BADGRSERVER: "https://localhost:8443"

volumes:
    db_data: {}